IGNORE_EVENT_TYPES = [
    "REQUEST_ALIVE",
    "CREATED_BY",
    "CHECK_CORS_PREFLIGHT_REQUIRED",
    "CHECK_CORS_PREFLIGHT_CACHE",
    "COMPUTED_PRIVACY_MODE",
    "COOKIE_INCLUSION_STATUS" ,
    "CORS_PREFLIGHT_RESULT",
    "CORS_PREFLIGHT_CACHED_RESULT",
    "DELEGATE_INFO",
    "NETWORK_DELEGATE_BEFORE_START_TRANSACTION",
    "HTTP_STREAM_JOB_BOUND_TO_REQUEST",
    "HTTP2_SESSION_UPDATE_RECV_WINDOW",
    "HTTP2_STREAM_UPDATE_RECV_WINDOW",
    "HTTP2_SESSION_SEND_WINDOW_UPDATE",
    "HTTP2_SESSION_RECV_DATA",
    "HTTP2_SESSION_RECV_SETTING",
    "HTTP_STREAM_JOB_CONTROLLER_BOUND" ,
    "HTTP_STREAM_REQUEST_BOUND_TO_JOB",
    "HTTP2_SESSION_POOL_FOUND_EXISTING_SESSION",
    "HTTP_STREAM_REQUEST_STARTED_JOB",
    "HTTP_STREAM_JOB_WAITING",
    "HTTP_STREAM_JOB_CONTROLLER_PROXY_SERVER_RESOLVED",
];

IGNORE_SOURCE_TYPES = [
    8 # SOCKET
]

PARAMS = [
    "initiator", 
    "url", 
    "method", 
    "headers", 
    "priority", 
    "source_dependency", 
    "address_list", 
    "phase", 
    "canonical_name", 
    "local_address",
    "time",
    "pac_string",
    "is_preconnect"
];

SOURCE_TYPES = {
    1 : "URL_REQUEST",
    8 : "SOCKET",
    9 : "HTTP2_SESSION",
    23 : "HTTP_STREAM_JOB_CONTROLLER",
    15 : "HTTP_STREAM_JOB",
#   ?? : "NETWORK_QUALITY_ESTIMATOR",
#   ?? : "DISK_CACHE_ENTRY",
#   ?? : "NONE", 
#   ?? : "PAC_FILE_DECIDER", 
#   ?? : "CERT_VERIFIER_JOB"
};

[
    "URL_REQUEST_DELEGATE_CERTIFICATE_REQUESTED", # 108,
    "URL_REQUEST_DELEGATE_RECEIVED_REDIRECT", # 109,
    "URL_REQUEST_DELEGATE_RESPONSE_STARTED", # 110,
    "URL_REQUEST_DELEGATE_SSL_CERTIFICATE_ERROR", # 111,
    "URL_REQUEST_FAKE_RESPONSE_HEADERS_CREATED", # 117,
    "URL_REQUEST_FILTERS_SET", # 118,
    "URL_REQUEST_JOB_BYTES_READ", # 113,
    "URL_REQUEST_JOB_FILTERED_BYTES_READ", # 114,
    "URL_REQUEST_REDIRECTED", # 104,
    "URL_REQUEST_REDIRECT_JOB", # 116,
    "URL_REQUEST_SET_PRIORITY", # 115,
    "URL_REQUEST_START_JOB", # 103,
]